INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (1, 'Anaheim Ducks', 'Mascot: Wild Wing');
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (2, 'Arizona Coyotes', 'Mascot: Howler the Coyote');
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (3, 'Boston Bruins', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (4, 'Buffalo Sabres', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (5, 'Calgary Flames', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (6, 'Carolina Hurricanes', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (7, 'Chicago Blackhawks', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (8, 'Colorado Avalanche', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (9, 'Columbus Blue Jackets', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (10, 'Dallas Stars', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (11, 'Detroit Red Wings', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (12, 'Edmonton Oilers', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (13, 'Florida Panthers', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (14, 'Los Angeles Kings', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (15, 'Minnesota Wild', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (16, 'Montreal Canadiens', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (17, 'Nashville Predators', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (18, 'New Jersey Devils', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (19, 'New York Islanders', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (20, 'New York Rangers', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (21, 'Ottawa Senators', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (22, 'Philadelphia Flyers', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (23, 'Pittsburgh Penguins', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (24, 'San Jose Sharks', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (25, 'Seattle Kraken', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (26, 'St Louis Blues', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (27, 'Tampa Bay Lightning', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (28, 'Toronto Maple Leafs', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (29, 'Vancouver Canucks', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (30, 'Vegas Golden Knights', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (31, 'Washington Capitals', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (32, 'Winnipeg Jets', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (33, 'Arizona Cardinals', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (34, 'Atlanta Falcons', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (35, 'Baltimore Ravens', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (36, 'Buffalo Bills', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (37, 'Carolina Panthers', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (38, 'Chicago Bears', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (39, 'Cincinnati Bengals', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (40, 'Cleveland Browns', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (41, 'Dallas Cowboys', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (42, 'Denver Broncos', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (43, 'Detroit Lions', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (44, 'Green Bay Packers', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (45, 'Houston Texans', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (46, 'Indianapolis Colts', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (47, 'Jacksonville Jaguars', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (48, 'Kansas City Chiefs', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (49, 'Las Vegas Raiders', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (50, 'Los Angeles Chargers', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (51, 'Los Angeles Rams', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (52, 'Miami Dolphins', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (53, 'Minnesota Vikings', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (54, 'New England Patriots', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (55, 'New Orleans Saints', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (56, 'New York Giants', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (57, 'New York Jets', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (58, 'Philadelphia Eagles', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (59, 'Pittsburgh Steelers', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (60, 'San Francisco 49ers', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (61, 'Seattle Seahawks', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (62, 'Tampa Bay Buccaneers', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (63, 'Tennessee Titans', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (64, 'Washington Football Team', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (65, 'Arizona Diamondbacks', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (66, 'Atlanta Braves', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (67, 'Baltimore Orioles', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (68, 'Boston Red Sox', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (69, 'Chicago White Sox', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (70, 'Chicago Cubs', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (71, 'Cincinnati Reds', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (72, 'Cleveland Indians', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (73, 'Colorado Rockies', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (74, 'Detroit Tigers', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (75, 'Houston Astros', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (76, 'Kansas City Royals', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (77, 'Los Angeles Angels', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (78, 'Los Angeles Dodgers', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (79, 'Miami Marlins', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (80, 'Milwaukee Brewers', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (81, 'Minnesota Twins', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (82, 'New York Yankees', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (83, 'New York Mets', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (84, 'Oakland Athletics', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (85, 'Philadelphia Phillies', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (86, 'Pittsburgh Pirates', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (87, 'San Diego Padres', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (88, 'San Francisco Giants', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (89, 'Seattle Mariners', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (90, 'St. Louis Cardinals', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (91, 'Tampa Bay Rays', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (92, 'Texas Rangers', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (93, 'Toronto Blue Jays', null);
INSERT INTO csc4500.sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) VALUES (94, 'Washington Nationals', null);