insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (1, 'Anaheim Ducks', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (2, 'Arizona Coyotes', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (3, 'Boston Bruins', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (4, 'Buffalo Sabres', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (5, 'Calgary Flames', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (6, 'Carolina Hurricanes', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (7, 'Chicago Blackhawks', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (8, 'Colorado Avalanche', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (9, 'Columbus Blue Jackets', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (10, 'Dallas Stars', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (11, 'Detroit Red Wings', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (12, 'Edmonton Oilers', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (13, 'Florida Panthers', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (14, 'Los Angeles Kings', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (15, 'Minnesota Wild', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (16, 'Montreal Canadiens', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (17, 'Nashville Predators', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (18, 'New Jersey Devils', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (19, 'New York Islanders', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (20, 'New York Rangers', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (21, 'Ottawa Senators', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (22, 'Philadelphia Flyers', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (23, 'Pittsburgh Penguins', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (24, 'San Jose Sharks', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (25, 'Seattle Kraken', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (26, 'St Louis Blues', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (27, 'Tampa Bay Lightning', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (28, 'Toronto Maple Leafs', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (29, 'Vancouver Canucks', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (30, 'Vegas Golden Knights', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (31, 'Washington Capitals', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (32, 'Winnipeg Jets', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (33, 'Arizona Cardinals', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (34, 'Atlanta Falcons', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (35, 'Baltimore Ravens', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (36, 'Buffalo Bills', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (37, 'Carolina Panthers', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (38, 'Chicago Bears', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (39, 'Cincinnati Bengals', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (40, 'Cleveland Browns', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (41, 'Dallas Cowboys', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (42, 'Denver Broncos', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (43, 'Detroit Lions', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (44, 'Green Bay Packers', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (45, 'Houston Texans', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (46, 'Indianapolis Colts', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (47, 'Jacksonville Jaguars', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (48, 'Kansas City Chiefs', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (49, 'Las Vegas Raiders', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (50, 'Los Angeles Chargers', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (51, 'Los Angeles Rams', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (52, 'Miami Dolphins', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (53, 'Minnesota Vikings', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (54, 'New England Patriots', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (55, 'New Orleans Saints', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (56, 'New York Giants', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (57, 'New York Jets', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (58, 'Philadelphia Eagles', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (59, 'Pittsburgh Steelers', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (60, 'San Francisco 49ers', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (61, 'Seattle Seahawks', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (62, 'Tampa Bay Buccaneers', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (63, 'Tennessee Titans', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (64, 'Washington Football Team', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (65, 'Arizona Diamondbacks', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (66, 'Atlanta Braves', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (67, 'Baltimore Orioles', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (68, 'Boston Red Sox', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (69, 'Chicago White Sox', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (70, 'Chicago Cubs', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (71, 'Cincinnati Reds', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (72, 'Cleveland Indians', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (73, 'Colorado Rockies', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (74, 'Detroit Tigers', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (75, 'Houston Astros', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (76, 'Kansas City Royals', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (77, 'Los Angeles Angels', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (78, 'Los Angeles Dodgers', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (79, 'Miami Marlins', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (80, 'Milwaukee Brewers', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (81, 'Minnesota Twins', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (82, 'New York Yankees', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (83, 'New York Mets', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (84, 'Oakland Athletics', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (85, 'Philadelphia Phillies', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (86, 'Pittsburgh Pirates', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (87, 'San Diego Padres', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (88, 'San Francisco Giants', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (89, 'Seattle Mariners', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (90, 'St. Louis Cardinals', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (91, 'Tampa Bay Rays', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (92, 'Texas Rangers', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (93, 'Toronto Blue Jays', null);
insert into sub_category (SubCategoryID, SubCat_Name, SubCat_Desc) values (94, 'Washington Nationals', null);
