insert into addresses (AddressID, A_Name, A_Address1, A_Address2, A_City, A_State, A_PostalCode, FK_UserID) values (1, 'Other', '3 Lawn Pass', null, 'Baltimore', 'Maryland', '21216', 22);
insert into addresses (AddressID, A_Name, A_Address1, A_Address2, A_City, A_State, A_PostalCode, FK_UserID) values (2, 'Other', '6819 Fair Oaks Avenue', null, 'Milwaukee', 'Wisconsin', '53234', 30);
insert into addresses (AddressID, A_Name, A_Address1, A_Address2, A_City, A_State, A_PostalCode, FK_UserID) values (3, 'Work', '48732 Di Loreto Way', null, 'Salt Lake City', 'Utah', '84199', 30);
insert into addresses (AddressID, A_Name, A_Address1, A_Address2, A_City, A_State, A_PostalCode, FK_UserID) values (4, 'Work', '718 Golf Course Parkway', 'APT 645', 'Columbus', 'Ohio', '43284', 13);
insert into addresses (AddressID, A_Name, A_Address1, A_Address2, A_City, A_State, A_PostalCode, FK_UserID) values (5, 'Other', '53737 Sullivan Park', null, 'Austin', 'Texas', '78778', 20);
insert into addresses (AddressID, A_Name, A_Address1, A_Address2, A_City, A_State, A_PostalCode, FK_UserID) values (6, 'School', '940 Bultman Junction', null, 'Bronx', 'New York', '10469', 25);
insert into addresses (AddressID, A_Name, A_Address1, A_Address2, A_City, A_State, A_PostalCode, FK_UserID) values (7, 'Other', '29319 Menomonie Trail', 'BLDG 123', 'Louisville', 'Kentucky', '40293', 6);
insert into addresses (AddressID, A_Name, A_Address1, A_Address2, A_City, A_State, A_PostalCode, FK_UserID) values (8, 'Home', '74 East Street', null, 'Albuquerque', 'New Mexico', '87180', 8);
insert into addresses (AddressID, A_Name, A_Address1, A_Address2, A_City, A_State, A_PostalCode, FK_UserID) values (9, 'Other', '27 Dapin Lane', 'BLDG 123', 'Loretto', 'Minnesota', '55598', 26);
insert into addresses (AddressID, A_Name, A_Address1, A_Address2, A_City, A_State, A_PostalCode, FK_UserID) values (10, 'Home', '8 Butternut Avenue', null, 'Los Angeles', 'California', '90060', 11);
insert into addresses (AddressID, A_Name, A_Address1, A_Address2, A_City, A_State, A_PostalCode, FK_UserID) values (11, 'Work', '7 Cordelia Court', null, 'Indianapolis', 'Indiana', '46278', 27);
insert into addresses (AddressID, A_Name, A_Address1, A_Address2, A_City, A_State, A_PostalCode, FK_UserID) values (12, 'Home', '51136 Springview Pass', null, 'Hartford', 'Connecticut', '06145', 15);
insert into addresses (AddressID, A_Name, A_Address1, A_Address2, A_City, A_State, A_PostalCode, FK_UserID) values (13, 'Work', '1 Ronald Regan Pass', 'BLDG 123', 'Kansas City', 'Missouri', '64114', 21);
insert into addresses (AddressID, A_Name, A_Address1, A_Address2, A_City, A_State, A_PostalCode, FK_UserID) values (14, 'Work', '071 Hovde Alley', null, 'Tyler', 'Texas', '75799', 2);
insert into addresses (AddressID, A_Name, A_Address1, A_Address2, A_City, A_State, A_PostalCode, FK_UserID) values (15, 'Home', '3245 Service Parkway', null, 'Phoenix', 'Arizona', '85067', 21);
insert into addresses (AddressID, A_Name, A_Address1, A_Address2, A_City, A_State, A_PostalCode, FK_UserID) values (16, 'Other', '55 Ruskin Hill', 'FL 4', 'Louisville', 'Kentucky', '40287', 29);
insert into addresses (AddressID, A_Name, A_Address1, A_Address2, A_City, A_State, A_PostalCode, FK_UserID) values (17, 'Other', '053 Oak Valley Lane', null, 'Carol Stream', 'Illinois', '60158', 9);
insert into addresses (AddressID, A_Name, A_Address1, A_Address2, A_City, A_State, A_PostalCode, FK_UserID) values (18, 'Other', '95 Golf Course Alley', null, 'Springfield', 'Illinois', '62794', 16);
insert into addresses (AddressID, A_Name, A_Address1, A_Address2, A_City, A_State, A_PostalCode, FK_UserID) values (19, 'Home', '4 Harbort Circle', null, 'Suffolk', 'Virginia', '23436', 9);
insert into addresses (AddressID, A_Name, A_Address1, A_Address2, A_City, A_State, A_PostalCode, FK_UserID) values (20, 'Other', '0 Bashford Plaza', null, 'Young America', 'Minnesota', '55573', 4);
insert into addresses (AddressID, A_Name, A_Address1, A_Address2, A_City, A_State, A_PostalCode, FK_UserID) values (21, 'Work', '770 Hayes Parkway', null, 'Wilmington', 'Delaware', '19810', 28);
insert into addresses (AddressID, A_Name, A_Address1, A_Address2, A_City, A_State, A_PostalCode, FK_UserID) values (22, 'Home', '28 Birchwood Center', null, 'Florence', 'South Carolina', '29505', 12);
insert into addresses (AddressID, A_Name, A_Address1, A_Address2, A_City, A_State, A_PostalCode, FK_UserID) values (23, 'Other', '8 Ridgeview Pass', null, 'Tempe', 'Arizona', '85284', 15);
insert into addresses (AddressID, A_Name, A_Address1, A_Address2, A_City, A_State, A_PostalCode, FK_UserID) values (24, 'Work', '3714 Carey Court', null, 'Columbus', 'Ohio', '43204', 22);
insert into addresses (AddressID, A_Name, A_Address1, A_Address2, A_City, A_State, A_PostalCode, FK_UserID) values (25, 'Other', '4 Erie Circle', null, 'New Haven', 'Connecticut', '06538', 17);
insert into addresses (AddressID, A_Name, A_Address1, A_Address2, A_City, A_State, A_PostalCode, FK_UserID) values (26, 'Home', '73 Cody Alley', null, 'Miami', 'Florida', '33129', 3);
insert into addresses (AddressID, A_Name, A_Address1, A_Address2, A_City, A_State, A_PostalCode, FK_UserID) values (27, 'Work', '08220 Stephen Pass', 'STE 22', 'Tacoma', 'Washington', '98447', 24);
insert into addresses (AddressID, A_Name, A_Address1, A_Address2, A_City, A_State, A_PostalCode, FK_UserID) values (28, 'Home', '00395 Lighthouse Bay Lane', null, 'Maple Plain', 'Minnesota', '55579', 22);
insert into addresses (AddressID, A_Name, A_Address1, A_Address2, A_City, A_State, A_PostalCode, FK_UserID) values (29, 'School', '3 Dorton Lane', null, 'Jamaica', 'New York', '11499', 24);
insert into addresses (AddressID, A_Name, A_Address1, A_Address2, A_City, A_State, A_PostalCode, FK_UserID) values (30, 'Other', '5129 International Crossing', 'FL 4', 'Houston', 'Texas', '77240', 27);
insert into addresses (AddressID, A_Name, A_Address1, A_Address2, A_City, A_State, A_PostalCode, FK_UserID) values (31, 'Other', '31 Merrick Trail', null, 'Anchorage', 'Alaska', '99522', 11);
insert into addresses (AddressID, A_Name, A_Address1, A_Address2, A_City, A_State, A_PostalCode, FK_UserID) values (32, 'School', '867 Commercial Center', null, 'Des Moines', 'Iowa', '50347', 25);
insert into addresses (AddressID, A_Name, A_Address1, A_Address2, A_City, A_State, A_PostalCode, FK_UserID) values (33, 'Other', '3667 Little Fleur Place', null, 'Kansas City', 'Missouri', '64101', 2);
insert into addresses (AddressID, A_Name, A_Address1, A_Address2, A_City, A_State, A_PostalCode, FK_UserID) values (34, 'School', '775 Marcy Point', null, 'Punta Gorda', 'Florida', '33982', 19);
insert into addresses (AddressID, A_Name, A_Address1, A_Address2, A_City, A_State, A_PostalCode, FK_UserID) values (35, 'Other', '97102 Schiller Pass', null, 'Honolulu', 'Hawaii', '96810', 14);
insert into addresses (AddressID, A_Name, A_Address1, A_Address2, A_City, A_State, A_PostalCode, FK_UserID) values (36, 'Work', '84 Village Drive', 'FL 4', 'San Mateo', 'California', '94405', 22);
insert into addresses (AddressID, A_Name, A_Address1, A_Address2, A_City, A_State, A_PostalCode, FK_UserID) values (37, 'Home', '5802 Weeping Birch Plaza', null, 'Oklahoma City', 'Oklahoma', '73197', 2);
insert into addresses (AddressID, A_Name, A_Address1, A_Address2, A_City, A_State, A_PostalCode, FK_UserID) values (38, 'Work', '2 Superior Plaza', null, 'Stockton', 'California', '95298', 23);
insert into addresses (AddressID, A_Name, A_Address1, A_Address2, A_City, A_State, A_PostalCode, FK_UserID) values (39, 'Work', '6 Warbler Alley', 'BLDG 123', 'Minneapolis', 'Minnesota', '55402', 14);
insert into addresses (AddressID, A_Name, A_Address1, A_Address2, A_City, A_State, A_PostalCode, FK_UserID) values (40, 'Home', '4972 Almo Circle', 'DEPT: IT', 'Columbus', 'Ohio', '43268', 13);
